version: "3.8"
services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    volumes:
      - ./backend/data:/app/data
      - ./backend/uploads:/app/uploads
    ports:
      - "4000:4000"
    depends_on:
      - dbmigrator

  dbmigrator:
    build: ./backend
    command: ["npm","run","migrate"]
    env_file: ./backend/.env
    volumes:
      - ./backend/data:/app/data

  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE=/api
    depends_on:
      - backend

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./ops/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./backend/uploads:/usr/share/nginx/html/uploads:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
